apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-eks-test-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: aws-eks-test
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: 'true'
      name: aws-eks-test-pod
      labels:
        app: aws-eks-test
    spec:
      containers:
        - name: aws-eks-test-container
          image: ramguguloth/aws-eks-test-image:v3.0
          env:
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_S3_REGION_NAME
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_S3_REGION_NAME
            - name: AWS_S3_CUSTOM_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: s3-config
                  key: AWS_S3_CUSTOM_DOMAIN
            - name: NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NAME
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: PASSWORD
            #- name: HOST
            #  valueFrom:
            #    secretKeyRef:
            #      name: db-secrets
            #      key: HOST
            - name: PORT
              value: "3306"
            - name: HOST
              value: db-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector-collector:4318"
            - name: OTEL_SERVICE_NAME
              value: "aws-eks-python-app"
          ports:
            - containerPort: 8000  