apiVersion: v1
kind: Service
metadata:
  name: aws-eks-test-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: aws-eks-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000