# Generated by Django 4.2.1 on 2023-06-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ac', models.TextField()),
                ('web', models.CharField(max_length=78)),
                ('contact', models.TextField(max_length=50)),
                ('em', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('salary', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('iorf', models.CharField(choices=[('I', 'internship'), ('F', 'freelancing')], max_length=1)),
                ('job_description', models.TextField()),
                ('req', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('level', models.CharField(choices=[('i', 'internship'), ('j', 'junior'), ('s', 'senior')], max_length=1)),
                ('remote', models.CharField(choices=[('f', 'full time'), ('c', 'contract'), ('p', 'part time')], max_length=1)),
                ('url', models.TextField()),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
