# Generated by Django 4.2.1 on 2023-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='em',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
