# Generated by Django 4.2.1 on 2023-06-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_company_contact_alter_company_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='company',
            name='follow',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
