# Generated by Django 4.2.1 on 2023-06-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_company_contact_company_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='follow',
            new_name='contact',
        ),
    ]
