# Generated by Django 4.2.1 on 2023-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_follow_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
